# Services
services:

    shop_extension:
            class: Shop\CommonBundle\Twig\ShopExtension
            arguments:
                entityManager: "@doctrine.orm.entity_manager"
            tags:
                - { name: twig.extension }
